apiVersion: v1
kind: Secret
metadata:
  name: argocd-infra-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: infra
  project: default
  url: git@github.com:Ilbertii/infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTXSdS5YCr+zlvKi5ZSnlh44xvWwgRl
    0CAZwj3oJks3CCenKgJJcVQgw/1GGZBnKV3LsnG85pJFkrJ6Uqt8yGIMAAAAoC0zuOotM7
    jqAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNdJ1LlgKv7OW8qL
    llKeWHjjG9bCBGXQIBnCPegmSzcIJ6cqAklxVCDD/UYZkGcpXcuycbzmkkWSsnpSq3zIYg
    wAAAAhAMRSToWhY1zmbgKyoIOMwrhgnqnXkGqTGpp9VZYLitl6AAAAAAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----

