apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LTEuZG9ja2VyLmlvIjp7InVzZXJuYW1lIjoiaWxiZXJ0aSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfSVlEM0JJenpySXpkaVJMNTdndGFrYi1LellNIiwiYXV0aCI6ImFXeGlaWEowYVRwa1kydHlYM0JoZEY5SldVUXpRa2w2ZW5KSmVtUnBVa3cxTjJkMFlXdGlMVXQ2V1UwPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: argocd-image-updater-backend
  namespace: argocd
type: kubernetes.io/dockerconfigjson
