apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-backend-git-writeback-creds
  namespace: argocd
stringData:
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTXSdS5YCr+zlvKi5ZSnlh44xvWwgRl
    0CAZwj3oJks3CCenKgJJcVQgw/1GGZBnKV3LsnG85pJFkrJ6Uqt8yGIMAAAAoC0zuOotM7
    jqAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNdJ1LlgKv7OW8qL
    llKeWHjjG9bCBGXQIBnCPegmSzcIJ6cqAklxVCDD/UYZkGcpXcuycbzmkkWSsnpSq3zIYg
    wAAAAhAMRSToWhY1zmbgKyoIOMwrhgnqnXkGqTGpp9VZYLitl6AAAAAAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----
